Refactor code and add test
CircleCI-Public/path-filtering-orb pull request #63
Opened 2022-12-05 20:34 UTC by h42zhu

This PR refactors the `create-parameters.py` code to be more functional and added a test to make sure the orb runs without errors. Testing for correctness requires more granular unit tests, which is generally omitted in other orbs.

2022-12-06 13:21 UTC, sulami requested changes

2022-12-06 13:21 UTC, sulami commented on src/scripts/create-parameters.py
> +  ]
This breaks support for mappings in files.

2022-12-06 13:21 UTC, sulami commented on src/scripts/create-parameters.py
> +    os.environ.get('MAPPING').splitlines()
This should not access the environment but use the mapping passed in.

2022-12-06 13:21 UTC, sulami commented on src/scripts/create-parameters.py
> +  write_mappings(mappings, output_path)
\~~~ It might be easier to unit test in the future if it returned the mappings as a string rather than writing to a file.

2022-12-12 16:32 UTC, elliotforbes approved these changes
LGTM!

2022-12-12 16:52 UTC, merged